### ISSUE TITLE
configure error: ".in'ig.status: error: cannot find input file: `Makefile"

### ISSUE THREAD

**Issue by asdftu** [man-pages-zh/manpages-zh#25] opened 2021-08-16 08:33 UTC
env:
wsl1 centos 7
gcc  8.3.1
opencc 1.1.2

run ./configure:
result:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for python3... yes
checking for opencc... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `Makefile

**Comment by hosiet** [comment] 2021-08-16 14:27
@asdftu could you post the full output during configuration?

1. The output of running `autoreconf --install --verbose --force`
2. Please provide the output of `ls` after the first step
3. Please provide the full output when running `configure`

**Comment by hosiet** [comment] 2021-10-01 02:54
Since I cannot reproduce this issue in WSL1 environment, I am closing this issue for now. Please feel free to reopen this issue when you provide more information.

**Closed by hosiet** 2021-10-01 02:54 UTC
